### PR TITLE
FLUID-5235: Add text about license to the footer of the docs.

### PR DESCRIPTION
**Pull request by acheetham**
@michelled, I took the form of the attribution from CC's site: http://creativecommons.org/choose/results-one?license_code=by&amp;jurisdiction=&amp;version=3.0&amp;lang=en

### CODE REVIEW

**Comment by jobara** [comment]
@acheetham and @michelled should we mention that the code snippets have a different licence. https://github.com/fluid-project/infusion/blob/master/Infusion-LICENSE.txt

**Comment by acheetham** [comment]
@michelled, @jobara, @colinbdclark: I've added the code license to the footer.

**Comment by jobara** [comment]
This PR is now out of date, given that it was filed 4.5 years ago it's held up pretty well. The main issue is that the license is now CC BY 4.0. I'm going to mothball this PR and we'll need to redo the work.

**Comment by jobara** [comment]
This has now been resolved in #310

**Pull request closed without merging**
