### PR TITLE
Refactored Infusion docs page from Docpad to Hugo

### PR DESCRIPTION
**Pull request by thisisobate**
@jobara @jhung I refactored the Infusion documentation page from docspad to Hugo static site. 

Attached below is a screenshot of what the hugo site looks like when running on local server

Screenshot (83)

At the moment, I'm still crafting the User Interface to suit the design guidelines. 

I'm yet to push the contents to the new Hugo site

Please review.

### CODE REVIEW

**Comment by jobara** [comment]
@thisisobate thanks for the work on this. However, the related [GSoC project](https://wiki.fluidproject.org/display/fluid/Google+Summer+of+Code+2020+with+the+Fluid+Project#GoogleSummerofCode2020withtheFluidProject-RefactorandAutomateInfusionDocumentation) is about splitting the content from the static site generator. It also requires some investigation into what the best SSG would be to use. Hugo was more of a suggestion, but there may be a better one to use.

**Comment by thisisobate** [comment]
> @thisisobate thanks for the work on this. However, the related [GSoC project](https://wiki.fluidproject.org/display/fluid/Google+Summer+of+Code+2020+with+the+Fluid+Project#GoogleSummerofCode2020withtheFluidProject-RefactorandAutomateInfusionDocumentation) is about splitting the content from the static site generator. It also requires some investigation into what the best SSG would be to use. Hugo was more of a suggestion, but there may be a better one to use.

@jobara  Please can you explain what you mean by splitting the content? 

Also, I actually thought of using Gatsby as my SSG of choice. According to research, it's one of the best SSG at the moment. I'll do more extensive research on how best Gatsby can power the platform. Looking forward to hearing from you.

**Comment by coderbabu10** [comment]
i think we can use jekyll what's your views @jobara ?

**Comment by jobara** [comment]
@coderbabu10 and @thisisobate it's better to move the discussion about the GSoC project to the [fluid-work mailing list](https://lists.idrc.ocad.ca/mailman/listinfo/fluid-work).

**Comment by thisisobate** [comment]
Alright. Would definitely do that. Thanks for the feedback @jobara

**Comment by jobara** [comment]
@thisisobate thanks for the work on this; however, we will be migrating to 11ty instead of Hugo.

**Pull request closed without merging**
