### PR TITLE
FLUID-5934: Correcting paths for prefs framework prefixes

### PR DESCRIPTION
**Pull request by jobara**
https://issues.fluidproject.org/browse/FLUID-5934

### CODE REVIEW

**Comment by cindyli** [comment]
Missed some places in APIChangesFrom1_5To2_0.md: line 255, 256, 293, 295

**Comment by jobara** [comment]
@cindyli I believe those were in the Infusion 1.5 version. I think this has changed for Infusion 2.0.

**Comment by cindyli** [comment]
That is certainly true. Thanks for catching it, Justin.

**Comment by cindyli** [comment]
Merged at 58e103d5becdc1799408b1c4ed6c591328de4ed7

**Pull request merged**
