### PR TITLE
FLUID-6229: Standardise markdown line lengths.

### PR DESCRIPTION
**Pull request by the-t-in-rtf**
See [FLUID-6229](https://issues.fluidproject.org/browse/FLUID-6229) for details.

### CODE REVIEW

**Comment by the-t-in-rtf** [comment]
This one should be simple to review and is over a month old now.  I was hoping @simonbates or someone who has previously reviewed my work here would have a little time to review.

**Comment by amb26** [comment]
Hi, sorry for leaving this on the pile, @the-t-in-rtf  - could you please make the minor updates to trunk and we should try to get this in as quickly as possible given it will conflict with everything

**Comment by the-t-in-rtf** [comment]
@amb26, I have merged in upstream/master and resolved the conflicts, this should be ready to go.

**Comment by amb26** [comment]
Some missing dependencies:
```
grunt lint
>> Local Npm module "grunt-markdownlint" not found. Is it installed?
>> Local Npm module "gpii-grunt-mdjson-lint" not found. Is it installed?
```

**Comment by the-t-in-rtf** [comment]
@amb26, the missing dependencies were a result of using too old a dev release of gpii-grunt-lint-all.  Upgrading to the full 1.0.5 release resolved those problems.  This should be ready for further review.

**Comment by the-t-in-rtf** [comment]
@amb26, I just merged with upstream master, incredibly there was only one conflict after a year of updates.  Can we merge this before anyone makes a bigger pass at updating the docs?

**Comment by the-t-in-rtf** [comment]
@amb26, I would like to start a spike to add a search to this project, it would be helpful to close this one out.

**Comment by amb26** [comment]
Cheers @the-t-in-rtf - sorry to leave this one the shelf so long. I wonder if you could backport some of the Windows support stuff from your test spike branch to here since I am unable to run the tests on Windows - 
````
> infusion-docs@1.5.0 pretest E:\source\gits\infusion-docs
> docpad generate --env static --out out
Access is denied.
npm ERR! Test failed.  See above for more details.
````
Whereas in your pull #147 the tests work correctly:

````
> infusion-docs@1.5.0 pretest E:\source\gits\infusion-docs
> node node_modules/docpad/bin/docpad generate --env static --out out

info: Welcome to DocPad v6.79.4 (local installation: E:\source\gits\infusion-docs\node_modules\docpad)
notice: Please donate to DocPad or have your company sponsor it: http://docpad.org/donate
````
etc

**Comment by the-t-in-rtf** [comment]
@amb26, give it a try now.

**Pull request merged**
